WebApp/Models/StorageLocationViewModel.cs
using Fr.EQL.AI110.DLD_GA.Entities;

namespace Fr.EQL.AI110.DLD_GA.WebApp.Models
{
    public class StorageLocationViewModel
    {
        public int StorLocationId { get; set; }
        public int PartnerId { get; set; }
        public int CityAndZipCodeId { get; set; }

        #region Data to display
        public List<Partner> Partners { get; set; }
        public List<StorageLocation> StorageLocations { get; set; }
        public List<StorageLocationDetails> Details { get; set; }
        public List<CityAndZipCode> CityAndZipCodes { get; set;}
        #endregion
    }
}

WebApp/Controllers/StorageLocationController.cs
using Fr.EQL.AI110.DLD_GA.Business;
using Fr.EQL.AI110.DLD_GA.Entities;
using Fr.EQL.AI110.DLD_GA.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;


namespace Fr.EQL.AI110.DLD_GA.WebApp.Controllers
{
    public class StorageLocationController : Controller
    {
        private IActionResult CreateStorageLocation(StorageLocation sl)
        {
            PartnerBusiness partnerBu = new PartnerBusiness();
            CityAndZipCodeBusiness cityBu=new CityAndZipCodeBusiness();
            List<Partner> partners = partnerBu.GetPartners();
            List<CityAndZipCode> cities = cityBu.GetCities();
            
            ViewBag.ListePartners = partners;
            ViewBag.ListeCities = cities;

            return View("Create", sl);
        }
        private IActionResult EditorStorageLocation(StorageLocation sl)
        {
            PartnerBusiness partnerBu = new PartnerBusiness();
            CityAndZipCodeBusiness cityBu = new CityAndZipCodeBusiness();
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            List<StorageLocation> sls = slBu.GetStorageLocations();
            List<Partner> partners = partnerBu.GetPartners();
            List<CityAndZipCode> cities = cityBu.GetCities();

            ViewBag.ListePartners = partners;
            ViewBag.ListeCities = cities;
            ViewBag.ListeSls = sls;

            return View("Edit", sl);
        }
        private IActionResult UpdateStorageLocation(StorageLocation sl)
        {
            PartnerBusiness partnerBu = new PartnerBusiness();
            CityAndZipCodeBusiness cityBu = new CityAndZipCodeBusiness();
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            List<StorageLocation> sls = slBu.GetStorageLocations();
            List<Partner> partners = partnerBu.GetPartners();
            List<CityAndZipCode> cities = cityBu.GetCities();

            ViewBag.ListePartners = partners;
            ViewBag.ListeCities = cities;
            ViewBag.ListeSls = sls;

            return View("Update", sl);
        }
        private IActionResult DeleteStorageLocation(StorageLocation sl)
        {
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            List<StorageLocation> sls = slBu.GetStorageLocations();
            ViewBag.ListeSls = sls;

            return View("Delete", sl);
        }
        public IActionResult Index()
        {
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            List<StorageLocation> sls = slBu.GetStorageLocations();
            return View(sls);
        }

        #region HttpGet
        [HttpGet]
        public IActionResult Create()
        { 
            return CreateStorageLocation(null);
        }
        [HttpGet]
        public IActionResult Update()
        {
            return UpdateStorageLocation(null);
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return DeleteStorageLocation(null);
        }
        [HttpGet]
        public IActionResult Edit()
        {
            PartnerBusiness partnerBu = new PartnerBusiness();
            CityAndZipCodeBusiness cityBu = new CityAndZipCodeBusiness();
            StorageLocationBusiness slBu = new StorageLocationBusiness();

            StorageLocationViewModel model = new StorageLocationViewModel();
            model.Partners = partnerBu.GetPartners();
            model.CityAndZipCodes = cityBu.GetCities();
            model.Details = slBu.GetStorageLocationInfos(0);
            return View(model);
        }
        #endregion HttpGet

        #region HttpPost
        [HttpPost]
        public IActionResult Delete(StorageLocation sl)
        {
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            slBu.DesactiveStorageLocation(sl);
            return RedirectToAction("Edit");
        }
        [HttpPost]
        public IActionResult Update(StorageLocation sl)
        {
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            slBu.UpdateStorageLocation(sl);
            return RedirectToAction("Edit");
        }
        [HttpPost]
        public IActionResult Create(StorageLocation sl)
        {
            StorageLocationBusiness storageLocationBU = new StorageLocationBusiness();
            storageLocationBU.SaveStorageLocation(sl);
            return RedirectToAction("Edit");
        }
        [HttpPost]
        public IActionResult Edit(StorageLocationViewModel model)
        {
            PartnerBusiness partnerBu = new PartnerBusiness();
            CityAndZipCodeBusiness cityBu = new CityAndZipCodeBusiness();
            StorageLocationBusiness slBu = new StorageLocationBusiness();

            model.Partners = partnerBu.GetPartners();
            model.CityAndZipCodes = cityBu.GetCities();
            model.Details = slBu.GetStorageLocationInfos(model.PartnerId);
            return View(model);
        }
        #endregion HttpPost

        #region Error
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion Error
    }
}

WebApp/Views/StorageLocation/Create.cshtml
<!DOCTYPE html>
<html>
@using Fr.EQL.AI110.DLD_GA.Entities;
@model StorageLocation
@{
    List<Partner> partners = ViewBag.ListePartners;
    List<CityAndZipCode> cities = ViewBag.ListeCities;
    StorageLocation sl = new StorageLocation();

}
<link href="@Href("~/css/DonationCreateView.css")" rel="StyleSheet" type="text/css" />

<h3 class="mb-3">Ajouter un lieu de stockage</h3>

<form method="post">
    <ul>
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="PartnerId"> Partenaire :</label>
            </div><div class="col-3">
                <select class="form-select" asp-for="PartnerId">
                    <option value="0">...</option>
                    @foreach (Partner partner in partners)
                    {
                        <option value="@partner.PartnerId">@partner.Appellation</option>
                    }
                </select>
            </div><div class="col-2">

                <label class="form-label" asp-for="CityAndZipCodeId"> Ville :</label>
            </div><div class="col-3">
                <select class="form-select" asp-for="CityAndZipCodeId">
                    <option value="0">...</option>
                    @foreach (CityAndZipCode cazc in cities)
                    {
                        <option value="@cazc.CityId">@cazc.City</option>
                    }
                </select>
            </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="StreetNameAndNumber"> Addresse complète :</label>
            </div><div class="col-3">  <input class="form-control" asp-for="StreetNameAndNumber" /> </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="Name"> Nom :</label>
            </div><div class="col-3"> <input class="form-control" asp-for="Name" /> </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="PhoneNumber"> Tel :</label>
            </div><div class="col-3"> <input class="form-control" asp-for="PhoneNumber"> </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="Picture"> Photo :</label>
            </div><div class="col-3">  <input class="form-control" asp-for="Picture" /> </div>
        </li>
        <br />
        <div class="row">
            <div class="col-10">
                <input type="submit" value="Enregistrer" class="btn btn-outline-dark mt-3 " style="float:right;" />
            </div>
        </div>
    </ul>
</form>

</html>

WebApp/Views/StorageLocation/Delete.cshtml
<!DOCTYPE html>
<html>
@using Fr.EQL.AI110.DLD_GA.Entities;
@model StorageLocation

@{
    List<StorageLocation> sls = ViewBag.ListeSls;
}
<link href="@Href("~/css/DonationCreateView.css")" rel="StyleSheet" type="text/css" />

<h3 class="mb-3">Supprimer un lieu de stockage</h3>

<form method="post">
    <li class="nav-item row  mt-3">
        <div class="col-3"><label asp-for="StorLocationId"> Nom du Lieu :</label>  </div>
        <div class="col-4">
            <select class="form-select" asp-for="StorLocationId">
                <option value="0">...</option>
                    @foreach (StorageLocation sl in sls)
                    {
                        <option value="@sl.StorLocationId">@sl.Name</option>
                    }
            </select>
        </div>
    </li>   <br />
    <div class="row">
        <div class="col-7">
            <input type="submit" value="Supprimer" class="btn btn-outline-dark mt-3 " style="float:right;" />
        </div>
    </div>

</form>

</html>

WebApp/Views/StorageLocation/Edit.cshtml
<!DOCTYPE html>
<html>
@using Fr.EQL.AI110.DLD_GA.Entities;
@using Fr.EQL.AI110.DLD_GA.WebApp.Models
@model StorageLocationViewModel

<link href="@Href("~/css/DonationCreateView.css")" rel="StyleSheet" type="text/css" />

<div class="row">
    <div class="col-4"><h4>Liste des lieux de stockage :</h4> </div>
    <div class="col-8 align-content-end" style="text-align: right;">
        <a asp-controller="StorageLocation"
           asp-action="Create" class="btn btn-outline-success">
            <i class="fas fa-plus"></i>&nbsp;Nouveau
        </a>
    </div>

</div>

<div class="row mt-3">
    <div class="col">
        <table center class="table table-striped">
            <tr>
                <th>Partenaire</th>
                <th>Ville</th>
                <th>Adresse</th>
                <th>Nom du stockage</th>
                <th>Téléphone</th>
              @*  <th>Photo</th>*@
            </tr>

            @foreach (StorageLocationDetails sl in Model.Details)
            {
                <tr>
                    <td>@sl.PartnerName </td>
                    <td>@sl.CityName</td>
                    <td>@sl.StreetNameAndNumber</td>
                    <td>@sl.Name</td>
                    <td>@sl.PhoneNumber</td>
                    @*<td>@sl.Picture</td>*@
                </tr>
            }

        </table>
    </div>
</div>
<div class="row mt-3">
    <div class="col" style="text-align: right;">
        <a asp-controller="StorageLocation"
           asp-action="Update" class="btn btn-outline-warning me-2">
            <i class="fas fa-edit"></i>&nbsp;
            Modifier
        </a>

        <a asp-controller="StorageLocation"
           asp-action="Delete" class="btn btn-outline-danger">
            <i class="fas fa-trash"></i>&nbsp;
            Supprimer
        </a>
    </div>

</div>

</html>

WebApp/Views/StorageLocation/Index.cshtml
<!DOCTYPE html>
<html>
@using Fr.EQL.AI110.DLD_GA.Entities;
@using Fr.EQL.AI110.DLD_GA.WebApp.Models;
@model List<Fr.EQL.AI110.DLD_GA.Entities.StorageLocation>
<link href="@Href("~/css/DonationCreateView.css")" rel="StyleSheet" type="text/css" />

  <h3>Liste des lieux de stockage :</h3>
  <table>
      <tr>
          <th>Partenaire</th>
          <th>Ville de stockage</th>
          <th>Nom du stockage</th>
          <th>Tel</th>
          <th>Picture</th>
          <th>Adresse</th>
      </tr>
      <h4>
          <a href="/storageLocation/Create">
          <button>Nouveau</button>
          </a>
      </h4>
  @foreach(StorageLocation sl in Model)
    {
        <tr>
            <td>@sl.PartnerId</td>
            <td>@sl.CityAndZipCodeId</td>
            <td>@sl.Name</td>
            <td>@sl.PhoneNumber</td>
            <td>@sl.Picture</td>
            <td>@sl.StreetNameAndNumber</td>            
        </tr>
    }
  </table>

</html>

WebApp/Views/StorageLocation/Update.cshtml
<!DOCTYPE html>
<html>
@using Fr.EQL.AI110.DLD_GA.Entities;
@model StorageLocation

@{
    List<Partner> partners = ViewBag.ListePartners;
    List<CityAndZipCode> cities = ViewBag.ListeCities;
    List<StorageLocation> sls = ViewBag.ListeSls;

}
<link href="@Href("~/css/DonationCreateView.css")" rel="StyleSheet" type="text/css" />


<h3>Modifier un lieu de stockage</h3>

<form method="post">
    <ul>
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="StorLocationId"> Nom du Lieu :</label>
            </div><div class="col-3">
            <select class="form-select" asp-for="StorLocationId">
                <option value="0">...</option>
                @foreach (StorageLocation sl in sls)
                {
                    <option value="@sl.StorLocationId">@sl.Name</option>
                }
            </select>
            </div>
        </li>
          <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="PartnerId"> Partenaire :</label>
            </div><div class="col-3">
                <select class="form-select" asp-for="PartnerId">
                    <option value="0">...</option>
                    @foreach (Partner partner in partners)
                    {
                        <option value="@partner.PartnerId">@partner.Appellation</option>
                    }
                </select>
            </div><div class="col-2">

                <label class="form-label" asp-for="CityAndZipCodeId"> Ville :</label>
            </div><div class="col-3">
                <select class="form-select" asp-for="CityAndZipCodeId">
                    <option value="0">...</option>
                    @foreach (CityAndZipCode cazc in cities)
                    {
                        <option value="@cazc.CityId">@cazc.City</option>
                    }
                </select>
            </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="StreetNameAndNumber"> Addresse complet :</label>
            </div><div class="col-3">  <input class="form-control" asp-for="StreetNameAndNumber" /> </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="Name"> Nom :</label>
            </div><div class="col-3"> <input class="form-control" asp-for="Name" /> </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="PhoneNumber"> Tel :</label>
            </div><div class="col-3"> <input class="form-control" asp-for="PhoneNumber"> </div>
        </li>
        <br />
        <li class="nav-item row">
            <div class="col-2">
                <label class="form-label" asp-for="Picture"> Photo :</label>
            </div><div class="col-3">  <input class="form-control" asp-for="Picture" /> </div>
        </li>
        <br />
        <div class="row">
            <div class="col-10">
                <input type="submit" value="Modifier" class="btn btn-outline-dark mt-3 " style="float:right;" />
            </div>
        </div>
    </ul>
</form>

</html>