WebApp/Controllers/CreditPurchaseController.cs
using Fr.EQL.AI110.DLD_GA.Business;
using Fr.EQL.AI110.DLD_GA.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.DLD_GA.WebApp.Controllers
{
    public class CreditPurchaseController : Controller
    {
        public IActionResult Index()
        {
            CreditPurchaseBusiness cBU = new CreditPurchaseBusiness();
            List<CreditPurchaseDetails> purchases = cBU.GetAllPurchaseDetails();

            return View(purchases);
        }
    }
}

WebApp/Controllers/DonationController.cs
using Fr.EQL.AI110.DLD_GA.Entities;
using Fr.EQL.AI110.DLD_GA.Business;
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GA.WebApp.Models;
namespace Fr.EQL.AI110.DLD_GA.WebApp.Controllers
{
    public class DonationController : Controller
    {
        #region SEARCH & BOOKING
        [HttpGet]
        public IActionResult Reservation(int id)
        {
            DonationSearchViewModel model = new DonationSearchViewModel();
            MemberBusiness mBU = new MemberBusiness();
            DonationBusiness dBu = new DonationBusiness();
            List<Member> members = mBU.SearchMembers();
            Donation don = dBu.GetDonationDetailsById(id);
            ViewBag.ListMembers = members;
            return View(don);
        }
        [HttpPost]
        public IActionResult Reservation(DonationDetails donDetails)
        {
            DonationBusiness dBu = new DonationBusiness();
            dBu.ReservedDonation(donDetails);
            return RedirectToAction("Booked");
        }
        public IActionResult Cancellation(DonationDetails donDetails)
        {
            DonationBusiness dBu = new DonationBusiness();
            dBu.CanceledDonation(donDetails);
            return RedirectToAction("Search");
        }

        [HttpGet]
        public IActionResult Booked()
        {
            DonationBusiness donBu = new DonationBusiness();
            MemberBusiness mBU = new MemberBusiness();
            ProductOriginBusiness poBu = new ProductOriginBusiness();
            CategoryBusiness cBU = new CategoryBusiness();
            CityAndZipCodeBusiness cityBU = new CityAndZipCodeBusiness();

            DonationSearchViewModel model = new DonationSearchViewModel();

            model.Cities = cityBU.GetCities();
            model.Members = mBU.SearchMembers();
            model.Origins = poBu.SearchOrigins();
            model.Categories = cBU.GetCategoriesInDepth();
            model.Donations = donBu.GetBookedDonations(0);

            bool isRegistered = false;
            model.AllDonations = new List<DonationDetails>();

            List<DonationDetails> list = donBu.GetBookedDonations(0);
            foreach (DonationDetails donDupli in list)
            {
                if (model.AllDonations != null)
                {
                    foreach (DonationDetails donFinal in model.AllDonations)
                    {
                        if (donFinal.RecipientId == donDupli.RecipientId)
                        {
                            isRegistered = true;
                            break;
                        }
                    }
                }
                if (isRegistered == false)
                {
                    model.AllDonations.Add(donDupli);
                }
                else
                {
                    isRegistered = false;
                }
            }
            return View(model);

        }
        [HttpPost]
        public IActionResult Booked(DonationSearchViewModel model)
        {
            DonationBusiness donBu = new DonationBusiness();
            MemberBusiness mBU = new MemberBusiness();
            ProductOriginBusiness poBu = new ProductOriginBusiness();
            CategoryBusiness cBU = new CategoryBusiness();
            CityAndZipCodeBusiness cityBU = new CityAndZipCodeBusiness();
            model.Cities = cityBU.GetCities();
            model.Members = mBU.SearchMembers();
            model.Origins = poBu.SearchOrigins();
            model.Categories = cBU.GetCategoriesInDepth();
            model.Donations = donBu.GetBookedDonations(model.MemberId);

            bool isRegistered = false;
            model.AllDonations = new List<DonationDetails>();

            List<DonationDetails> list = donBu.GetBookedDonations(0);
            foreach (DonationDetails donDupli in list)
            {
                if (model.AllDonations != null)
                {
                    foreach (DonationDetails donFinal in model.AllDonations)
                    {
                        if (donFinal.RecipientId == donDupli.RecipientId)
                        {
                            isRegistered = true;
                            break;
                        }
                    }
                }
                if (isRegistered == false)
                {
                    model.AllDonations.Add(donDupli);
                }
                else
                {
                    isRegistered = false;
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Search()
        {
            DonationBusiness donBu = new DonationBusiness();
            MemberBusiness mBU = new MemberBusiness();
            ProductOriginBusiness poBu = new ProductOriginBusiness();
            CategoryBusiness cBU = new CategoryBusiness();
            CityAndZipCodeBusiness cityBU = new CityAndZipCodeBusiness();

            DonationSearchViewModel model = new DonationSearchViewModel();

            model.Cities = cityBU.GetCities();
            model.Members = mBU.SearchMembers();
            model.Origins = poBu.SearchOrigins();
            model.Categories = cBU.GetCategoriesInDepth();
            model.Donations = donBu.GetDonations(0, "", 0, 0, 0);
            return View(model);
        }


        [HttpPost]
        public IActionResult Search(DonationSearchViewModel model)
        {
            DonationBusiness donBu = new DonationBusiness();
            MemberBusiness mBU = new MemberBusiness();
            ProductOriginBusiness poBu = new ProductOriginBusiness();
            CategoryBusiness cBU = new CategoryBusiness();
            CityAndZipCodeBusiness cityBU = new CityAndZipCodeBusiness();
            model.Cities = cityBU.GetCities();
            model.Members = mBU.SearchMembers();
            model.Origins = poBu.SearchOrigins();
            model.Categories = cBU.GetCategoriesInDepth();
            model.Donations = donBu.GetDonations(model.ProductOriginId, model.City, model.ZipCode, model.StorageId, model.ProductId);
            return View(model);
        }
        #endregion

        #region SUBMIT
        [HttpGet]
        public IActionResult Create()
        {
            MemberBusiness mBU = new MemberBusiness();
            ProductOriginBusiness poBu = new ProductOriginBusiness();
            CategoryBusiness catBU = new CategoryBusiness();

            DonationCreationViewModel model = new DonationCreationViewModel();
            model.Don = new Donation();
            model.Members = mBU.SearchMembers();
            model.Origins = poBu.SearchOrigins();
            model.Categories = catBU.GetCategoriesInDepth();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(DonationCreationViewModel previousModel)
        {
            CityAndZipCodeBusiness cityBU = new CityAndZipCodeBusiness();
            MemberBusiness mBU = new MemberBusiness();
            ProductBusiness poBu = new ProductBusiness();
            UnitBusiness unitBU = new UnitBusiness();
            StorageBusiness stoBU = new StorageBusiness();

            DonationPlaceSelectionViewModel newModel = new DonationPlaceSelectionViewModel();
            newModel.Cities = cityBU.GetCities();
            newModel.Don = previousModel.Don;
            newModel.Donor = mBU.GetMemberDetailsById(previousModel.Don.DonorId);

            Product product = poBu.GetproductById(previousModel.Don.ProductId);
            newModel.ProductName = product.Name;

            Unit unit = unitBU.GetUnitById(previousModel.Don.UnitId);
            newModel.UnitName = unit.Name;

            newModel.AvailableStoragesForProduct = stoBU.GetAvailableStoragesByPreservationMethod(product.PreservationId);

            return View("PlaceSelection", newModel);

        }

        [HttpPost]
        public IActionResult OpeningHours(DonationPlaceSelectionViewModel oldModel)
        {
            try
            {
                WeekdayBusiness wBU = new WeekdayBusiness();
                OpeningHoursBusiness hoursBU = new OpeningHoursBusiness();
                DonationBusiness donBU = new DonationBusiness();
                int donId = donBU.SaveDonationId(oldModel.Don);


                DonationOpeningHoursCreationViewModel newModel = new DonationOpeningHoursCreationViewModel();
                newModel.Weekdays = wBU.GetWeekdays();
                newModel.Don = donBU.GetDonationDetailsById(donId);
                newModel.AllOpeningHours = hoursBU.GetAllHoursDetailsByDonationId(donId);

                return View(newModel);
            }
            catch (Exception ex)
            {
                MemberBusiness mBU = new MemberBusiness();
                ProductOriginBusiness poBu = new ProductOriginBusiness();
                CategoryBusiness catBU = new CategoryBusiness();

                DonationCreationViewModel model = new DonationCreationViewModel();
                model.Don = new Donation();
                model.Don.Quantity = oldModel.Don.Quantity;
                model.Members = mBU.SearchMembers();
                model.Origins = poBu.SearchOrigins();
                model.Categories = catBU.GetCategoriesInDepth();

                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Create", model);
            }
            
        }
        [HttpPost]
        public IActionResult LoopOpeningHours(DonationOpeningHoursCreationViewModel model)
        {
            WeekdayBusiness wBU = new WeekdayBusiness();
            OpeningHoursBusiness hoursBU = new OpeningHoursBusiness();
            DonationBusiness donBU = new DonationBusiness();

            model.ThisDayOpeningHours.DonationId = model.Don.Id;
            hoursBU.SaveOpeningHours(model.ThisDayOpeningHours);

            model.Don = donBU.GetDonationDetailsById(model.Don.Id);

WebApp/Controllers/OpeningDaysAndHoursController.cs
using Fr.EQL.AI110.DLD_GA.Business;
using Fr.EQL.AI110.DLD_GA.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.DLD_GA.WebApp.Controllers
{
    public class OpeningDaysAndHoursController : Controller
    {
        private IActionResult EditerOpeningTime(OpeningHours openTime)
        {
            StorageLocationBusiness slBu = new StorageLocationBusiness();
            List<StorageLocation> sls = slBu.GetStorageLocations();
            ViewBag.ListeStorageLocations = sls;
            StorageBusiness storageBu = new StorageBusiness();
            List<Storage> storages = storageBu.GetStorages();
            ViewBag.ListeStorages = storages;
            WeekdayBusiness wdayBu = new WeekdayBusiness();
            List<Weekday> wDays = wdayBu.GetWeekdays();
            ViewBag.ListeWeekdays = wDays;

            return View("Create", openTime);
        }

        #region HttpGet
        [HttpGet]
        public IActionResult Create()
        {
            return EditerOpeningTime(null);
        }
        #endregion HttpGet

        #region HttpPost
        [HttpPost]
        public IActionResult Create(OpeningHours openTime)
        {
            Weekday wday= new Weekday();
            OpeningHoursBusiness openTimeBU = new OpeningHoursBusiness();
            openTimeBU.SaveOpeningHours(openTime);
            return RedirectToAction("Create");
        }
        #endregion 

    }
}

WebApp/Controllers/StorageController.cs
using Fr.EQL.AI110.DLD_GA.Business;
using Fr.EQL.AI110.DLD_GA.Entities;
using Fr.EQL.AI110.DLD_GA.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.DLD_GA.WebApp.Controllers
{
    public class StorageController : Controller
    {
        private IActionResult CreateStorage(Storage st)
        {
            StorageLocationBusiness slbu = new StorageLocationBusiness();
            PreservationMethodBusiness pmbu = new PreservationMethodBusiness();
            StorageDimensionsBusiness sdbu = new StorageDimensionsBusiness();
            StorageAccessibilityBusiness sabu = new StorageAccessibilityBusiness();

            List<PreservationMethod> methods = pmbu.GetPreservationMethod();
            List<StorageDimensions> dimensions = sdbu.GetStorageDimensions();
            List<StorageLocation> locations = slbu.GetStorageLocations();
            List<StorageAccessibility> acces = sabu.GetStorageAccessibility();

            ViewBag.ListeLocations = locations;
            ViewBag.ListeMethods = methods;
            ViewBag.ListeDimensions = dimensions;
            ViewBag.ListeAccessibilities = acces;

            return View("Create", st);
        }
        private IActionResult UpdateStorage(Storage st)
        {
            StorageBusiness bu = new StorageBusiness();
            StorageLocationBusiness slbu = new StorageLocationBusiness();
            PreservationMethodBusiness pmbu = new PreservationMethodBusiness();
            StorageDimensionsBusiness sdbu = new StorageDimensionsBusiness();
            StorageAccessibilityBusiness sabu = new StorageAccessibilityBusiness();

            List<Storage> storages = bu.GetStorages();
            List<PreservationMethod> methods = pmbu.GetPreservationMethod();
            List<StorageDimensions> dimensions = sdbu.GetStorageDimensions();
            List<StorageLocation> locations = slbu.GetStorageLocations();
            List<StorageAccessibility> acces = sabu.GetStorageAccessibility();

            ViewBag.ListeStorages = storages;
            ViewBag.ListeLocations = locations;
            ViewBag.ListeMethods = methods;
            ViewBag.ListeDimensions = dimensions;
            ViewBag.ListeAccessibilities = acces;

            return View("Update", st);
        }
        private IActionResult DeleteStorage(Storage st)
        {
            StorageBusiness bu = new StorageBusiness();
            List<Storage> storages = bu.GetStorages();
            ViewBag.ListeStorages = storages;

            return View("Delete", st);
        }
        public IActionResult Index()
        {
            StorageBusiness bu = new StorageBusiness();
            List<Storage> sts = bu.GetStorages();
            return View(sts);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return CreateStorage(null);
        }
        [HttpGet]
        public IActionResult Update()
        {
            return UpdateStorage(null);
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return DeleteStorage(null);
        }
        [HttpGet]
        public IActionResult Edit()
        {
        
                StorageLocationBusiness slbu = new StorageLocationBusiness();
                PreservationMethodBusiness pmbu = new PreservationMethodBusiness();
                StorageDimensionsBusiness sdbu = new StorageDimensionsBusiness();
                StorageAccessibilityBusiness sabu = new StorageAccessibilityBusiness();
                StorageBusiness bu = new StorageBusiness();
                StorageViewModel model = new StorageViewModel();

                model.Locations = slbu.GetStorageLocations();
                model.Methods = pmbu.GetPreservationMethod();
                model.Dimensions = sdbu.GetStorageDimensions();
                model.Accessibilities = sabu.GetStorageAccessibility();
                model.Details = bu.GetStorageInfos(0);
                return View(model);
        }
        [HttpPost]
        public IActionResult Create(Storage st)
        {
            StorageBusiness bu = new StorageBusiness();
            bu.SaveStorage(st);
            return RedirectToAction("Edit");
        }
        [HttpPost]
        public IActionResult Delete(Storage st)
        {
            StorageBusiness bu = new StorageBusiness();
            bu.DesactiveStorage(st);
            return RedirectToAction("Edit");
        }
        [HttpPost]
        public IActionResult Update(Storage st)
        {
            StorageBusiness bu = new StorageBusiness();
            bu.UpdateStorage(st);
            return RedirectToAction("Edit");
        }
        [HttpPost]
        public IActionResult Edit(StorageViewModel model)
        {
            StorageLocationBusiness slbu = new StorageLocationBusiness();
            PreservationMethodBusiness pmbu = new PreservationMethodBusiness();
            StorageDimensionsBusiness sdbu = new StorageDimensionsBusiness();
            StorageAccessibilityBusiness sabu = new StorageAccessibilityBusiness();
            StorageBusiness bu = new StorageBusiness();

            model.Locations = slbu.GetStorageLocations();
            model.Methods= pmbu.GetPreservationMethod();
            model.Dimensions= sdbu.GetStorageDimensions();
            model.Accessibilities = sabu.GetStorageAccessibility();
            model.Details = bu.GetStorageInfos(model.StorLocationId);
            return View(model);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
@{
    string ErrorMessage = "";

    if (TempData.ContainsKey("ErrorMessage"))
    {
        ErrorMessage = (string)TempData["ErrorMessage"];
    }
}

<!DOCTYPE html>
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8314201c6e.js" crossorigin="anonymous"></script>
    <style type="text/css">
        .adherent a.dropdown-toggle {
            color: #198754 !important;
            border-color: #198754;
        }

        .partenaire a.dropdown-toggle {
            color: #dc3545 !important;
            border-color: #dc3545;
        }

        .administrateur a.dropdown-toggle {
            color: #ffc107 !important;
            border-color: #ffc107;
        }

        .comment-fonctionne a {
            color: chocolate !important;
        }

        .errorMessage {
             color:red;
             font-size:1.2em;
             border:red solid 2px;
             border-radius:10px; 
             padding:0.1em;
        }
        
    </style>
    <meta charset="utf-8">

    <title>Home</title>

</head>

<body>


      <header>
        <nav class="navbar navbar-expand-md  navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="~/">
                    <img src="~/images/logo_dld.png" alt="" width="56">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item dropdown adherent p-2">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-apple-alt"></i> Fonctions adhérent
                            </a>
                            <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Donation" asp-action="Create">
                                        Proposer un
                                        don
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Donation" asp-action="Search">
                                        Consulter les dons
                                        proposés
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Donation" asp-action="Booked">Consulter les dons réservés</a>
                                </li>
                                @*               <li>
                                    <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Se mettre en absent</a></li>*@
                                    <li>
                                    <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="CreditPurchase" asp-action="Index">Afficher les achats de crédits</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown partenaire p-2">
                            <a href="" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                                <i class="fas fa-carrot"></i>
                                Fonctions partenaire
                            </a>
                            <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton2">
                               @* <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="StorageLocation" asp-action="Create">Ajouter un lieu de stockage</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>*@
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="StorageLocation" asp-action="Edit">
                                        Consulter la liste des lieux de
                                        stockage
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="OpeningDaysAndHours" asp-action="Create">
                                        Ajouter un horaire à un lieu de
                                        stockage
                                    </a>
                                </li>
                                @*<li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Storage" asp-action="Create">
                                        Ajouter un emplacement de
                                        stockage
                                    </a>
                                </li>*@
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Storage" asp-action="Edit">
                                        Consulter la liste des emplacements de
                                        stockage
                                    </a>
                                </li>
                            </ul>

                        </li>
                       @* <li class="nav-item dropdown administrateur p-2">
                            <a href="" class="nav-link dropdown-toggle " data-bs-toggle="dropdown">
                                <i class="fas fa-lemon"></i>
                                Fonctions administrateur
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">
                                        Valider l'inscription d'un
                                        partenraire
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Suivre les signalements</a>
                                </li>
                            </ul>

                        </li>*@

                        <li class="comment-fonctionne nav-item p-2">
                            <a href="" class="nav-link"><i class="fas fa-leaf"></i> Comment cela fonctionne ?</a>
                        </li>

                    </ul>
                </div>




            </div>
        </nav>
        
        <img style="max-width:100vw;"src="~/images/bandeau.png">
        @if (ErrorMessage != "")
        {
                <div>
                    <p style="padding:0.1em;margin:1em;"><span class="errorMessage"> @ErrorMessage </span></p>
                </div>

        }
    </header>


    <div class="container">

        <main role="main" class="pb-5 mb-5 mt-3">
            <div class="row">
                <div class="col">
                    @RenderBody()
                </div>
            </div>
        </main>

    </div>

    <footer class="">
        <nav class="navbar fixed-bottom navbar-expand-l  navbar-dark bg-dark">
            <div class="container-fluid">
                <ul class="nav  mx-auto">
                    <li class="nav-item"><a href="#" class="nav-link  text-light">Mentions légales</a></li>
                    <li class="nav-item"><a href="#" class="nav-link  text-light">FAQs</a></li>
                    <li class="nav-item"><a href="#" class="nav-link text-light ">Qui sommes-nous ?</a></li>

                </ul>
                <span class="navbar-text text-light">
                    &copy; 2021 DLD
                </span>
            </div>
        </nav>

    </footer>

</body>

</html>